// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	Token  string             `db:"token" json:"token"`
	Data   []byte             `db:"data" json:"data"`
	Expiry pgtype.Timestamptz `db:"expiry" json:"expiry"`
}

type User struct {
	ID           int64              `db:"id" json:"id"`
	Email        string             `db:"email" json:"email"`
	PasswordHash string             `db:"password_hash" json:"-"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
