// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	Token  string             `db:"token" json:"token"`
	Data   []byte             `db:"data" json:"data"`
	Expiry pgtype.Timestamptz `db:"expiry" json:"expiry"`
}

type User struct {
	ID        int64              `db:"id" json:"id"`
	Sub       string             `db:"sub" json:"-"`
	Provider  string             `db:"provider" json:"-"`
	Email     string             `db:"email" json:"email"`
	FirstName pgtype.Text        `db:"first_name" json:"first_name"`
	LastName  pgtype.Text        `db:"last_name" json:"last_name"`
	AvatarUrl pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
