// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blocks.richtext.sql

package repository

import (
	"context"
)

const createRichTextBlock = `-- name: CreateRichTextBlock :one
INSERT INTO
    blocks.richtext (content, format)
VALUES
    ($1, $2)
RETURNING
    id, content, format, created_at, updated_at
`

type CreateRichTextBlockParams struct {
	Content string `db:"content" json:"content"`
	Format  string `db:"format" json:"format"`
}

func (q *Queries) CreateRichTextBlock(ctx context.Context, arg CreateRichTextBlockParams) (BlocksRichtext, error) {
	row := q.db.QueryRow(ctx, createRichTextBlock, arg.Content, arg.Format)
	var i BlocksRichtext
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.Format,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRichTextBlock = `-- name: DeleteRichTextBlock :exec
DELETE FROM
    blocks.richtext
WHERE
    id = $1
`

func (q *Queries) DeleteRichTextBlock(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteRichTextBlock, id)
	return err
}

const getRichTextBlock = `-- name: GetRichTextBlock :one
SELECT
    id, content, format, created_at, updated_at
FROM
    blocks.richtext
WHERE
    id = $1
`

func (q *Queries) GetRichTextBlock(ctx context.Context, id int64) (BlocksRichtext, error) {
	row := q.db.QueryRow(ctx, getRichTextBlock, id)
	var i BlocksRichtext
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.Format,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRichTextBlock = `-- name: UpdateRichTextBlock :one
UPDATE
    blocks.richtext
SET
    content = $1,
    format = $2
WHERE
    id = $3
RETURNING
    id, content, format, created_at, updated_at
`

type UpdateRichTextBlockParams struct {
	Content string `db:"content" json:"content"`
	Format  string `db:"format" json:"format"`
	ID      int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateRichTextBlock(ctx context.Context, arg UpdateRichTextBlockParams) (BlocksRichtext, error) {
	row := q.db.QueryRow(ctx, updateRichTextBlock, arg.Content, arg.Format, arg.ID)
	var i BlocksRichtext
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.Format,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
