// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blocks.sql

package repository

import (
	"context"
)

const listBlocks = `-- name: ListBlocks :many
SELECT
    code, label, description, created_at
FROM
    reference.block_types
`

func (q *Queries) ListBlocks(ctx context.Context) ([]ReferenceBlockType, error) {
	rows, err := q.db.Query(ctx, listBlocks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReferenceBlockType
	for rows.Next() {
		var i ReferenceBlockType
		if err := rows.Scan(
			&i.Code,
			&i.Label,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
