// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blocks_hero.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHeroBlock = `-- name: CreateHeroBlock :one
INSERT INTO
    blocks_hero (
        heading,
        subheading,
        cta_label,
        cta_url
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4
    )
RETURNING
    id, heading, subheading, cta_label, cta_url, created_at, updated_at
`

type CreateHeroBlockParams struct {
	Heading    string      `db:"heading" json:"heading"`
	Subheading pgtype.Text `db:"subheading" json:"subheading"`
	CtaLabel   pgtype.Text `db:"cta_label" json:"cta_label"`
	CtaUrl     pgtype.Text `db:"cta_url" json:"cta_url"`
}

func (q *Queries) CreateHeroBlock(ctx context.Context, arg CreateHeroBlockParams) (BlocksHero, error) {
	row := q.db.QueryRow(ctx, createHeroBlock,
		arg.Heading,
		arg.Subheading,
		arg.CtaLabel,
		arg.CtaUrl,
	)
	var i BlocksHero
	err := row.Scan(
		&i.ID,
		&i.Heading,
		&i.Subheading,
		&i.CtaLabel,
		&i.CtaUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteHeroBlock = `-- name: DeleteHeroBlock :exec
DELETE FROM
    blocks_hero
WHERE
    id = $1
`

func (q *Queries) DeleteHeroBlock(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteHeroBlock, id)
	return err
}

const getHeroBlock = `-- name: GetHeroBlock :one
SELECT
    id, heading, subheading, cta_label, cta_url, created_at, updated_at
FROM
    blocks_hero
WHERE
    id = $1
`

func (q *Queries) GetHeroBlock(ctx context.Context, id int64) (BlocksHero, error) {
	row := q.db.QueryRow(ctx, getHeroBlock, id)
	var i BlocksHero
	err := row.Scan(
		&i.ID,
		&i.Heading,
		&i.Subheading,
		&i.CtaLabel,
		&i.CtaUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHeroBlock = `-- name: UpdateHeroBlock :one
UPDATE
    blocks_hero
SET
    heading = $1,
    subheading = $2,
    cta_label = $3,
    cta_url = $4
WHERE
    id = $5
RETURNING
    id, heading, subheading, cta_label, cta_url, created_at, updated_at
`

type UpdateHeroBlockParams struct {
	Heading    string      `db:"heading" json:"heading"`
	Subheading pgtype.Text `db:"subheading" json:"subheading"`
	CtaLabel   pgtype.Text `db:"cta_label" json:"cta_label"`
	CtaUrl     pgtype.Text `db:"cta_url" json:"cta_url"`
	ID         int64       `db:"id" json:"id"`
}

func (q *Queries) UpdateHeroBlock(ctx context.Context, arg UpdateHeroBlockParams) (BlocksHero, error) {
	row := q.db.QueryRow(ctx, updateHeroBlock,
		arg.Heading,
		arg.Subheading,
		arg.CtaLabel,
		arg.CtaUrl,
		arg.ID,
	)
	var i BlocksHero
	err := row.Scan(
		&i.ID,
		&i.Heading,
		&i.Subheading,
		&i.CtaLabel,
		&i.CtaUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
