// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pages.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPage = `-- name: CreatePage :one
INSERT INTO
    pages (
        title,
        slug,
        STATUS,
        seo_title,
        seo_description
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5
    )
RETURNING
    id, title, slug, status, seo_title, seo_description, created_at, updated_at
`

type CreatePageParams struct {
	Title          string      `db:"title" json:"title"`
	Slug           string      `db:"slug" json:"slug"`
	Status         string      `db:"status" json:"status"`
	SeoTitle       pgtype.Text `db:"seo_title" json:"seo_title"`
	SeoDescription pgtype.Text `db:"seo_description" json:"seo_description"`
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (Page, error) {
	row := q.db.QueryRow(ctx, createPage,
		arg.Title,
		arg.Slug,
		arg.Status,
		arg.SeoTitle,
		arg.SeoDescription,
	)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Status,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteByID = `-- name: DeleteByID :exec
DELETE FROM
    pages
WHERE
    id = $1
`

func (q *Queries) DeleteByID(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteByID, id)
	return err
}

const deleteBySlug = `-- name: DeleteBySlug :exec
DELETE FROM
    pages
WHERE
    slug = $1
`

func (q *Queries) DeleteBySlug(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, deleteBySlug, slug)
	return err
}

const getPageByID = `-- name: GetPageByID :one
SELECT
    id, title, slug, status, seo_title, seo_description, created_at, updated_at
FROM
    pages
WHERE
    id = $1
`

func (q *Queries) GetPageByID(ctx context.Context, id int64) (Page, error) {
	row := q.db.QueryRow(ctx, getPageByID, id)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Status,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPageBySlug = `-- name: GetPageBySlug :one
SELECT
    id, title, slug, status, seo_title, seo_description, created_at, updated_at
FROM
    pages
WHERE
    slug = $1
`

func (q *Queries) GetPageBySlug(ctx context.Context, slug string) (Page, error) {
	row := q.db.QueryRow(ctx, getPageBySlug, slug)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Status,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPages = `-- name: ListPages :many
SELECT
    id, title, slug, status, seo_title, seo_description, created_at, updated_at
FROM
    pages
ORDER BY
    created_at DESC
`

func (q *Queries) ListPages(ctx context.Context) ([]Page, error) {
	rows, err := q.db.Query(ctx, listPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Page
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Status,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePage = `-- name: UpdatePage :one
UPDATE
    pages
SET
    title = $1,
    slug = $2,
    STATUS = $3,
    seo_title = $4,
    seo_description = $5
WHERE
    slug = $2
RETURNING
    id, title, slug, status, seo_title, seo_description, created_at, updated_at
`

type UpdatePageParams struct {
	Title          string      `db:"title" json:"title"`
	Slug           string      `db:"slug" json:"slug"`
	Status         string      `db:"status" json:"status"`
	SeoTitle       pgtype.Text `db:"seo_title" json:"seo_title"`
	SeoDescription pgtype.Text `db:"seo_description" json:"seo_description"`
}

func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) (Page, error) {
	row := q.db.QueryRow(ctx, updatePage,
		arg.Title,
		arg.Slug,
		arg.Status,
		arg.SeoTitle,
		arg.SeoDescription,
	)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Status,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
