// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pages_blocks.sql

package repository

import (
	"context"
)

const addBlockToPage = `-- name: AddBlockToPage :one
INSERT INTO
    pages_blocks (
        page_id,
        block_id,
        block_collection,
        sort_order
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4
    )
RETURNING
    id, page_id, block_id, block_collection, sort_order, hide_block, created_at, updated_at
`

type AddBlockToPageParams struct {
	PageID          int64  `db:"page_id" json:"page_id"`
	BlockID         int64  `db:"block_id" json:"block_id"`
	BlockCollection string `db:"block_collection" json:"block_collection"`
	SortOrder       int32  `db:"sort_order" json:"sort_order"`
}

func (q *Queries) AddBlockToPage(ctx context.Context, arg AddBlockToPageParams) (PagesBlock, error) {
	row := q.db.QueryRow(ctx, addBlockToPage,
		arg.PageID,
		arg.BlockID,
		arg.BlockCollection,
		arg.SortOrder,
	)
	var i PagesBlock
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.BlockID,
		&i.BlockCollection,
		&i.SortOrder,
		&i.HideBlock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePageBlock = `-- name: DeletePageBlock :exec
DELETE FROM
    pages_blocks
WHERE
    id = $1
`

func (q *Queries) DeletePageBlock(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePageBlock, id)
	return err
}

const getPageBlocks = `-- name: GetPageBlocks :many
SELECT
    id, page_id, block_id, block_collection, sort_order, hide_block, created_at, updated_at
FROM
    pages_blocks
WHERE
    page_id = $1
ORDER BY
    sort_order ASC
`

func (q *Queries) GetPageBlocks(ctx context.Context, pageID int64) ([]PagesBlock, error) {
	rows, err := q.db.Query(ctx, getPageBlocks, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PagesBlock
	for rows.Next() {
		var i PagesBlock
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.BlockID,
			&i.BlockCollection,
			&i.SortOrder,
			&i.HideBlock,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderPageBlocks = `-- name: ReorderPageBlocks :exec
UPDATE
    pages_blocks
SET
    sort_order = $1
WHERE
    id = $2
`

type ReorderPageBlocksParams struct {
	SortOrder int32 `db:"sort_order" json:"sort_order"`
	ID        int64 `db:"id" json:"id"`
}

func (q *Queries) ReorderPageBlocks(ctx context.Context, arg ReorderPageBlocksParams) error {
	_, err := q.db.Exec(ctx, reorderPageBlocks, arg.SortOrder, arg.ID)
	return err
}

const updatePageBlock = `-- name: UpdatePageBlock :one
UPDATE
    pages_blocks
SET
    hide_block = $1,
    sort_order = $2
WHERE
    id = $3
RETURNING
    id, page_id, block_id, block_collection, sort_order, hide_block, created_at, updated_at
`

type UpdatePageBlockParams struct {
	HideBlock bool  `db:"hide_block" json:"hide_block"`
	SortOrder int32 `db:"sort_order" json:"sort_order"`
	ID        int64 `db:"id" json:"id"`
}

func (q *Queries) UpdatePageBlock(ctx context.Context, arg UpdatePageBlockParams) (PagesBlock, error) {
	row := q.db.QueryRow(ctx, updatePageBlock, arg.HideBlock, arg.SortOrder, arg.ID)
	var i PagesBlock
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.BlockID,
		&i.BlockCollection,
		&i.SortOrder,
		&i.HideBlock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
